# Generated by Django 3.0 on 2019-12-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='WordListAPI',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word_phrase', models.CharField(max_length=50)),
                ('high_rating_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('low_rating_score', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
