# Generated by Django 3.0.2 on 2020-01-07 02:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yelp', '0005_auto_20200106_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraping_test1',
            name='user_id',
        ),
        migrations.AddField(
            model_name='scraping_test1',
            name='id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scraping_test1',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 21, 43, 54, 785613)),
        ),
    ]
